#include "stdafx.h"

#include "component_info.h"

DECLARE_COMPONENT_VERSION(OPENSUBSONIC_COMPONENT_NAME,
                          OPENSUBSONIC_COMPONENT_VERSION,
                          OPENSUBSONIC_COMPONENT_ABOUT);

VALIDATE_COMPONENT_FILENAME(OPENSUBSONIC_COMPONENT_NAME ".dll");

FOOBAR2000_IMPLEMENT_CFG_VAR_DOWNGRADE;
